#!/usr/bin/env bash
#
# dsh-markdown-input v1 真机重测向导。
# Generated by the /wizard skill.
#
# Walks a human through loading the plugin into a real dsh web instance and
# verifying every behavior the v1 spec promised. Results are recorded
# progressively into outputs/retest-<timestamp>.md and can be posted to
# issue #1 at the end.
#
# Run from anywhere:  bash scripts/retest-wizard.sh
# Everything above the "STAGES" marker is the wizard library: do not hand-edit.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

# Run from the repo root no matter where the script lives, so the report
# lands in outputs/ and the link: install path is stable.
cd "$(dirname "$0")/.."

REPO_WIN='D:\csdiy\AIcode\dsh-markdown-input'
REPORT="outputs/retest-$(date +%Y%m%d-%H%M).md"
PASS=(); FAIL=(); SKIP=()

# record NAME RESULT NOTE appends one verdict to the report and the tally.
record() {
  local name="$1" result="$2" note="${3:-}"
  case "$result" in
    PASS) PASS+=("$name"); printf '  %s✓ PASS%s %s\n' "$GREEN" "$RESET" "$name" ;;
    FAIL) FAIL+=("$name"); printf '  %s✗ FAIL%s %s\n' "$RED" "$RESET" "$name" ;;
    *)    SKIP+=("$name"); printf '  %s- SKIP%s %s\n' "$YELLOW" "$RESET" "$name" ;;
  esac
  {
    printf '\n## %s — %s\n' "$name" "$result"
    if [[ -n "$note" ]]; then printf '\n> %s\n' "$note"; fi
  } >> "$REPORT"
  return 0
}

# ask_result NAME walks the human through one verification and records it.
ask_result() {
  local name="$1" reply="" note=""
  while true; do
    printf '  %s结果？%s [p=通过 / f=失败 / s=跳过] ' "$YELLOW" "$RESET"
    read -r reply || true
    # Full-width letters too: a live IME turns p/f/s into ｐ/ｆ/ｓ.
    case "$reply" in
      p|P|ｐ|Ｐ) reply=PASS; break ;;
      f|F|ｆ|Ｆ) reply=FAIL; break ;;
      s|S|ｓ|Ｓ) reply=SKIP; break ;;
      *) : ;;
    esac
  done
  printf '  %s备注（可空，直接 Enter）:%s ' "$DIM" "$RESET"
  read -r note || true
  record "$name" "$reply" "$note"
  pause "（Enter 继续）"
}

mkdir -p outputs
{
  printf '# dsh-markdown-input v1 真机重测\n\n'
  printf -- '- 时间: %s\n' "$(date '+%Y-%m-%d %H:%M')"
  printf -- '- 提交: %s\n' "$(git rev-parse --short HEAD 2>/dev/null || echo '(unknown)')"
} > "$REPORT"

TOTAL_STAGES=10

banner "dsh-markdown-input 真机重测"

# ── Stage 1: 构建、安装、启动 ─────────────────────────────────────────────
stage "构建与安装"
say "目标：让一个真实 dsh web 实例加载本插件。"
step "构建产物（lib/ 已存在时可跳过）：cd \"$REPO_WIN\" 然后 pnpm build"
step "本地 link 安装：dsh plugin --profile web add link:\"$REPO_WIN\""
note "  （若 dsh 不认 Windows 路径形式，改试 link:D:/csdiy/AIcode/dsh-markdown-input，以 dsh 报错提示为准）"
step "启动：dsh web  （浏览器打开 http://127.0.0.1:3080）"
open_url "http://127.0.0.1:3080"
say "验收：聊天输入区被插件接管 —— 出现「渲染」按钮和等宽编辑面。"
note "  （未接管的话：看 dsh 启动日志里有没有 markdown-input；再跑 cordis_inspect what:\"client\" 查注册情况）"
ask_result "安装与接管"

# ── Stage 2: 渲染模式折叠 ─────────────────────────────────────────────────
stage "渲染模式折叠"
step "新建会话，在输入区输入三行："
note "  # 大标题"
note "  **粗体** 和 \`行内代码\`"
note "  - [ ] 一个任务"
step "光标停在最后一行：第一行的 # 应折叠、标题变大、任务项出现复选框。"
step "光标移回第一行：# 标记恢复可见可编辑。"
ask_result "渲染模式折叠"

# ── Stage 3: 模式切换与持久化 ─────────────────────────────────────────────
stage "模式切换与持久化"
step "点工具行的「源码」按钮：全部语法标记以原文显示，占位提示变「Markdown 源码…」。"
step "F5 刷新页面：输入区仍应停留在源码模式。"
step "点「渲染」切回：折叠恢复。"
ask_result "模式切换与持久化"

# ── Stage 4: 键位与 IME ───────────────────────────────────────────────────
stage "键位与 IME"
step "空输入区：Enter 不发送（发送按钮应为禁用态）。"
step "输入 hello 按 Enter：消息发送，输入区清空。"
step "新消息里按 Shift+Enter：换行不发送。"
step "输入 \`\`\` 后按 Enter：换行（进入代码围栏），不发送。"
step "切中文输入法，打 nihao，候选框打开时按 Enter：候选上屏，不发送消息。"
ask_result "键位与 IME"

# ── Stage 5: 粘贴转换 ─────────────────────────────────────────────────────
stage "粘贴转换"
step "在浏览器里打开任一网页，复制一段富文本（含标题、列表、链接）。"
step "粘贴进输入区：应变成干净 Markdown（# 标题、- 列表、[文本](链接)），无 HTML 残留。"
step "再复制同样内容，按 Ctrl+Shift+V 粘贴：应为纯文本原文，不经转换。"
ask_result "粘贴转换"

# ── Stage 6: 用户消息 Markdown 化 ─────────────────────────────────────────
stage "用户消息 Markdown 化"
step "发送一条消息，内容包含：# 标题 一行、**粗体**、以及两行 - 列表。"
step "看聊天气泡：应按 Markdown 渲染（大字标题、粗体、列表），而不是纯文本。"
ask_result "用户消息 Markdown 化"

# ── Stage 7: 引用 chip ────────────────────────────────────────────────────
stage "引用 chip"
step "发送一条带 @提及 或 /技能 或会话引用（@[标签](dsh-session:…)）的消息。"
step "看气泡：引用 chip（图标+标签）应保留在 Markdown 渲染结果里。"
note "  （已知取舍：句中的 chip 会把所在段落分块；消息开头/结尾的 chip 应无缝。）"
ask_result "引用 chip"

# ── Stage 8: 抢占与草稿幸存 ───────────────────────────────────────────────
stage "抢占与草稿幸存"
step "在输入区留一句草稿（不要发送）。"
step "触发一个会弹审批/提问面板的会话（如让子代理跑一个需要批准的任务）。"
step "面板出现时输入区被内置面板接管；结束后插件输入区应恢复，且草稿还在。"
ask_result "抢占与草稿幸存"

# ── Stage 9: 视觉细节 ─────────────────────────────────────────────────────
stage "视觉细节"
step "围栏代码块：等宽字体 + 底色（无语言级高亮）。"
step "- [ ] 任务项渲染为复选框样式（勾选项带对勾）。"
step "链接：下划线样式。"
step "贴 30 行长文本：输入区自动增高，超过约 14 行后内部滚动，不撑爆界面。"
step "界面切到 English：按钮/占位文案随语言切换。"
ask_result "视觉细节"

# ── Stage 10: 汇总 ────────────────────────────────────────────────────────
stage "汇总"
{
  printf '\n## 汇总\n\n'
  printf -- '- PASS: %s\n' "${#PASS[@]}"
  printf -- '- FAIL: %s\n' "${#FAIL[@]}"
  printf -- '- SKIP: %s\n' "${#SKIP[@]}"
  (( ${#FAIL[@]} )) && { printf '\n失败项：\n'; for f in "${FAIL[@]}"; do printf -- '- %s\n' "$f"; done; }
  true
} >> "$REPORT"

printf '\n  %s结果%s  PASS=%s  FAIL=%s  SKIP=%s\n' "$BOLD" "$RESET" "${#PASS[@]}" "${#FAIL[@]}" "${#SKIP[@]}"
note "报告已写入 $REPORT"

if (( ${#FAIL[@]} )); then
  note "失败项下一步：gh issue create 逐条开单，或用 /diagnosing-bugs 定位。"
fi

if confirm "把重测结果评论到 issue #1？"; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh api repos/long6177/dsh-markdown-input/issues/1/comments -F body=@"$REPORT" --jq .html_url; then
      printf '  %s✓ 已评论%s\n' "$GREEN" "$RESET"
    else
      SKIPPED+=("评论 issue #1（手动：gh api repos/long6177/dsh-markdown-input/issues/1/comments -F body=@$REPORT）")
      warn "评论失败（账号权限或网络），可手动重发"
    fi
  else
    SKIPPED+=("评论 issue #1（gh 未就绪；手动：gh api repos/long6177/dsh-markdown-input/issues/1/comments -F body=@$REPORT）")
    warn "gh 不可用，未评论"
  fi
fi

finish
